/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeTestRouteImport } from './routes/theme-test'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as CentresRouteImport } from './routes/centres'
import { Route as BeginRouteImport } from './routes/begin'
import { Route as AdvantageRouteImport } from './routes/advantage'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammesMathematicsRouteImport } from './routes/programmes.mathematics'
import { Route as ProgrammesKidsRouteImport } from './routes/programmes.kids'
import { Route as ProgrammesEnglishRouteImport } from './routes/programmes.english'
import { Route as ProgrammesChineseRouteImport } from './routes/programmes.chinese'

const ThemeTestRoute = ThemeTestRouteImport.update({
  id: '/theme-test',
  path: '/theme-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresRoute = CentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginRoute = BeginRouteImport.update({
  id: '/begin',
  path: '/begin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvantageRoute = AdvantageRouteImport.update({
  id: '/advantage',
  path: '/advantage',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesMathematicsRoute = ProgrammesMathematicsRouteImport.update({
  id: '/mathematics',
  path: '/mathematics',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesKidsRoute = ProgrammesKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesEnglishRoute = ProgrammesEnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesChineseRoute = ProgrammesChineseRouteImport.update({
  id: '/chinese',
  path: '/chinese',
  getParentRoute: () => ProgrammesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advantage': typeof AdvantageRoute
  '/begin': typeof BeginRoute
  '/centres': typeof CentresRoute
  '/comments': typeof CommentsRoute
  '/partners': typeof PartnersRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/theme-test': typeof ThemeTestRoute
  '/programmes/chinese': typeof ProgrammesChineseRoute
  '/programmes/english': typeof ProgrammesEnglishRoute
  '/programmes/kids': typeof ProgrammesKidsRoute
  '/programmes/mathematics': typeof ProgrammesMathematicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advantage': typeof AdvantageRoute
  '/begin': typeof BeginRoute
  '/centres': typeof CentresRoute
  '/comments': typeof CommentsRoute
  '/partners': typeof PartnersRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/theme-test': typeof ThemeTestRoute
  '/programmes/chinese': typeof ProgrammesChineseRoute
  '/programmes/english': typeof ProgrammesEnglishRoute
  '/programmes/kids': typeof ProgrammesKidsRoute
  '/programmes/mathematics': typeof ProgrammesMathematicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advantage': typeof AdvantageRoute
  '/begin': typeof BeginRoute
  '/centres': typeof CentresRoute
  '/comments': typeof CommentsRoute
  '/partners': typeof PartnersRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/theme-test': typeof ThemeTestRoute
  '/programmes/chinese': typeof ProgrammesChineseRoute
  '/programmes/english': typeof ProgrammesEnglishRoute
  '/programmes/kids': typeof ProgrammesKidsRoute
  '/programmes/mathematics': typeof ProgrammesMathematicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advantage'
    | '/begin'
    | '/centres'
    | '/comments'
    | '/partners'
    | '/programmes'
    | '/theme-test'
    | '/programmes/chinese'
    | '/programmes/english'
    | '/programmes/kids'
    | '/programmes/mathematics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advantage'
    | '/begin'
    | '/centres'
    | '/comments'
    | '/partners'
    | '/programmes'
    | '/theme-test'
    | '/programmes/chinese'
    | '/programmes/english'
    | '/programmes/kids'
    | '/programmes/mathematics'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advantage'
    | '/begin'
    | '/centres'
    | '/comments'
    | '/partners'
    | '/programmes'
    | '/theme-test'
    | '/programmes/chinese'
    | '/programmes/english'
    | '/programmes/kids'
    | '/programmes/mathematics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvantageRoute: typeof AdvantageRoute
  BeginRoute: typeof BeginRoute
  CentresRoute: typeof CentresRoute
  CommentsRoute: typeof CommentsRoute
  PartnersRoute: typeof PartnersRoute
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  ThemeTestRoute: typeof ThemeTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-test': {
      id: '/theme-test'
      path: '/theme-test'
      fullPath: '/theme-test'
      preLoaderRoute: typeof ThemeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres': {
      id: '/centres'
      path: '/centres'
      fullPath: '/centres'
      preLoaderRoute: typeof CentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begin': {
      id: '/begin'
      path: '/begin'
      fullPath: '/begin'
      preLoaderRoute: typeof BeginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advantage': {
      id: '/advantage'
      path: '/advantage'
      fullPath: '/advantage'
      preLoaderRoute: typeof AdvantageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/mathematics': {
      id: '/programmes/mathematics'
      path: '/mathematics'
      fullPath: '/programmes/mathematics'
      preLoaderRoute: typeof ProgrammesMathematicsRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/kids': {
      id: '/programmes/kids'
      path: '/kids'
      fullPath: '/programmes/kids'
      preLoaderRoute: typeof ProgrammesKidsRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/english': {
      id: '/programmes/english'
      path: '/english'
      fullPath: '/programmes/english'
      preLoaderRoute: typeof ProgrammesEnglishRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/chinese': {
      id: '/programmes/chinese'
      path: '/chinese'
      fullPath: '/programmes/chinese'
      preLoaderRoute: typeof ProgrammesChineseRouteImport
      parentRoute: typeof ProgrammesRoute
    }
  }
}

interface ProgrammesRouteChildren {
  ProgrammesChineseRoute: typeof ProgrammesChineseRoute
  ProgrammesEnglishRoute: typeof ProgrammesEnglishRoute
  ProgrammesKidsRoute: typeof ProgrammesKidsRoute
  ProgrammesMathematicsRoute: typeof ProgrammesMathematicsRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesChineseRoute: ProgrammesChineseRoute,
  ProgrammesEnglishRoute: ProgrammesEnglishRoute,
  ProgrammesKidsRoute: ProgrammesKidsRoute,
  ProgrammesMathematicsRoute: ProgrammesMathematicsRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvantageRoute: AdvantageRoute,
  BeginRoute: BeginRoute,
  CentresRoute: CentresRoute,
  CommentsRoute: CommentsRoute,
  PartnersRoute: PartnersRoute,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  ThemeTestRoute: ThemeTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
